groups:
    - general
    - bash
    - dev-aws
    - developer
    - dev-blog
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - sudoalt::default
attributes:
    dotfiles:
        vimusers:
            - root
            - david
        kdeploy:
            hostname: dev
    git:
        name: David Williams
        email: david.williams@dualspark.com
    osxdefaults:
        computername: davidwilliams-dev
    authorization:
        sudo:
            users:
                - david
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - speedtest_cli
        cask_apps:
            - python3
            - joinme
