groups:
    - general
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    homebrewalt:
        cask_apps:
            - google-chrome
            - firefox
        cask_fonts:
            - ubuntu-mono-powerline
            - ubuntu
            - lato
            - source-sans-pro
