recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_unhide_home
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - pyenv-virtualenv
            - pyenv-virtualenvwrapper
            - pyenv-pip-migrate
            - awscli
        cask_apps:
            - vagrant
            - vagrant-manager
            - vagrant-bar
            - virtualbox
            - python
            - packer

