recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
    mac_os_x:
        - applications::sublime_text_3
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - awscli
        cask_apps:
            - transmit
        gems:
            - jekyll

