recipes:
    mac_os_x:
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
        cask_apps:
            - virtualbox
